//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTC_versionORANGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Information
    {
        public int Client_ID { get; set; }
        public string Client_Code { get; set; }
        public string Client_Short_Name { get; set; }
        public string Client_Full_Name { get; set; }
        public Nullable<int> Approach_Year { get; set; }
        public string EM_Code { get; set; }
        public string EM_Full_Name { get; set; }
        public string CL_Field_Code { get; set; }
        public string CL_Field_Full_Name { get; set; }
        public string Client_Phone { get; set; }
        public string Client_website { get; set; }
        public string Client_mail { get; set; }
        public string Client_Owner { get; set; }
        public string Client_Owner_Phone { get; set; }
        public string Client_Owner_Email { get; set; }
        public string Client_Principal { get; set; }
        public string Client_Principal_Phone { get; set; }
        public string Client_Principal_Email { get; set; }
        public string Address_Detail { get; set; }
        public Nullable<int> Address_District { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
