//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTC_versionORANGE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PTCEntities : DbContext
    {
        public PTCEntities()
            : base("name=PTCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Information> Client_Information { get; set; }
        public virtual DbSet<EM_List> EM_List { get; set; }
        public virtual DbSet<Ref_District> Ref_District { get; set; }
        public virtual DbSet<Ref_Province> Ref_Province { get; set; }
        public virtual DbSet<Ref_Region> Ref_Region { get; set; }
        public virtual DbSet<User_Basic> User_Basic { get; set; }
    
        public virtual ObjectResult<string> Check_EMPosition(string user_Code)
        {
            var user_CodeParameter = user_Code != null ?
                new ObjectParameter("User_Code", user_Code) :
                new ObjectParameter("User_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Check_EMPosition", user_CodeParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> Check_Login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("Check_Login", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> Check_Role(string usercode)
        {
            var usercodeParameter = usercode != null ?
                new ObjectParameter("usercode", usercode) :
                new ObjectParameter("usercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Check_Role", usercodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Find_Region_By_District(Nullable<int> district_ID)
        {
            var district_IDParameter = district_ID.HasValue ?
                new ObjectParameter("District_ID", district_ID) :
                new ObjectParameter("District_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Find_Region_By_District", district_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> FindIDbyUserCode(string user_Code)
        {
            var user_CodeParameter = user_Code != null ?
                new ObjectParameter("User_Code", user_Code) :
                new ObjectParameter("User_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FindIDbyUserCode", user_CodeParameter);
        }
    }
}
