//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTC_versionORANGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Region()
        {
            this.Ref_Province = new HashSet<Ref_Province>();
        }
    
        public int Region_ID { get; set; }
        public string Region_Full_Name { get; set; }
        public string Region_Short_Name { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Province> Ref_Province { get; set; }
    }
}
